define openvpn::server (
  $server,
  $netmask,
  $proto = 'udp',
  $port = 1194,
  $dev = 'tun',
  $topology = 'subnet',
  $user = 'nobody',
  $group = 'nogroup',
  $ca = undef,
  $cert = undef,
  $key = undef,
  $crl = undef,
  $ta = undef,
  $ta_content = undef,
  $dh = undef,
  $status = true,
  $status_version = 2,
  $ipp = undef,
  $max_clients = undef,
  $mute = undef,
  $plugins = [],
  $push = [],
) {
  openvpn::config { $title:
    role           => 'server',
    server         => $server,
    netmask        => $netmask,
    proto          => $proto,
    port           => $port,
    dev            => $dev,
    topology       => $topology,
    user           => $user,
    group          => $group,
    ca             => $ca,
    cert           => $cert,
    key            => $key,
    crl            => $crl,
    ta             => $ta,
    ta_content     => $ta_content,
    dh             => $dh,
    status         => $status,
    status_version => $status_version,
    ipp            => $ipp,
    plugins        => $plugins,
    push           => $push,
  }
}
