define openvpn::server (
  $server_network,
  $server_netmask,
  $proto = 'udp',
  $port = 1194,
  $dev = 'tun',
  $topology = 'subnet',
  $user = 'nobody',
  $group = 'nogroup',
  $ca = undef,
  $cert = undef,
  $key = undef,
  $crl_verify_file = undef,
  $tls_auth_enabled = undef,
  $tls_auth_content = undef,
  $tls_auth_file = undef,
  $dh = undef,
  $status = true,
  $status_version = 2,
  $verb = 3,
  $ifconfig_pool_persist_enabled = undef,
  $ifconfig_pool_persist_file = undef,
  $max_clients = undef,
  $mute = undef,
  $plugins = [],
  $push = [],
  $manage_service = true,
) {
  openvpn::config { $title:
    role                          => 'server',
    server_network                => $server_network,
    server_netmask                => $server_netmask,
    proto                         => $proto,
    port                          => $port,
    dev                           => $dev,
    topology                      => $topology,
    user                          => $user,
    group                         => $group,
    ca                            => $ca,
    cert                          => $cert,
    key                           => $key,
    crl_verify_file               => $crl_verify_file,
    tls_auth_enabled              => $tls_auth_enabled,
    tls_auth_content              => $tls_auth_content,
    tls_auth_file                 => $tls_auth_file,
    dh                            => $dh,
    status                        => $status,
    status_version                => $status_version,
    ifconfig_pool_persist_enabled => $ifconfig_pool_persist_enabled,
    ifconfig_pool_persist_file    => $ifconfig_pool_persist_file,
    plugins                       => $plugins,
    push                          => $push,
    verb                          => $verb,
    manage_service                => $manage_service,
  }
}
