define openvpn::server (
  $server,
  $netmask,
  $proto = 'udp',
  $port = 1194,
  $dev = 'tun',
  $topology = 'subnet',
  $user = 'nobody',
  $group = 'nogroup',
  $ca = undef,
  $cert = undef,
  $key = undef,
  $crl = undef,
  $tls_auth_enabled = undef,
  $tls_auth_content = undef,
  $tls_auth_file = undef,
  $dh = undef,
  $status = true,
  $status_version = 2,
  $verb = 3,
  $ipp = undef,
  $max_clients = undef,
  $mute = undef,
  $plugins = [],
  $push = [],
) {
  openvpn::config { $title:
    role             => 'server',
    server           => $server,
    netmask          => $netmask,
    proto            => $proto,
    port             => $port,
    dev              => $dev,
    topology         => $topology,
    user             => $user,
    group            => $group,
    ca               => $ca,
    cert             => $cert,
    key              => $key,
    crl              => $crl,
    tls_auth_enabled => $tls_auth_enabled,
    tls_auth_content => $tls_auth_content,
    tls_auth_file    => $tls_auth_file,
    dh               => $dh,
    status           => $status,
    status_version   => $status_version,
    ipp              => $ipp,
    plugins          => $plugins,
    push             => $push,
    verb             => $verb,
  }
}
